Repository STACKPOT/STACKPOT-FE, pull requests merged in 2025-01, with the labels that each got.

#3 [Feature/#1] 헤더, 공통 TextField 및 Button UI 구현
  index.html
  src/assets/svgs/index.ts
  src/assets/svgs/logo.svg
  src/components/commons/.gitkeep
  src/components/commons/Button/Button.style.ts
  src/components/commons/Button/Button.tsx
  src/components/commons/TextField/TextField.style.ts
  src/components/commons/TextField/TextField.tsx
  src/components/index.ts
  src/components/layouts/Header/Header.style.ts
  src/components/layouts/Header/Header.tsx
  src/styles/theme.ts
Labels: 🌱 Add, ✨ Feat

#7 [Feature/#6] 페이지 라우팅 설정
  package.json
  src/App.tsx
  src/components/commons/TextField/TextField.style.ts
  src/components/layouts/Header/Header.style.ts
  src/constants/routes.ts
  src/main.tsx
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
  src/pages/Landing/Landing.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/homes/.gitkeep
  src/pages/index.ts
  src/pages/myPages/.gitkeep
  src/routes/router.tsx
  src/styles/theme.ts
  yarn.lock
Labels: 🧹 Chore, ✨ Feat

#13 [Feature/#10] 공개 범위 설정, 가입하기 버튼 추가
  src/components/commons/Button/SignupButton.style.ts
  src/components/commons/Button/SignupButton.tsx
  src/components/forms/.gitkeep
  src/components/forms/SelectableField/SelectableField.style.ts
  src/components/forms/SelectableField/SelectableField.tsx
  src/components/index.ts
  src/components/layouts/.gitkeep
Labels: ✨ Feat

#15 [Refactor/#14] 사이드바 리팩토링 및 라우팅 추가
  index.html
  src/assets/svgs/home.svg
  src/assets/svgs/index.ts
  src/assets/svgs/myPot.svg
  src/assets/svgs/pot.svg
  src/assets/svgs/profile.svg
  src/assets/svgs/setUp.svg
  src/components/layouts/SideBar/SideBar.style.ts
  src/components/layouts/SideBar/SideBar.tsx
  src/constants/routes.ts
  src/pages/MyPot/MyPot.tsx
  src/pages/Pot/Pot.tsx
  src/pages/Setting/Setting.tsx
  src/routes/router.tsx
  src/styles/global.ts
Labels: 🌱 Add, ♻️ Refactor, 💄 Style

#19 [Style/#17] theme - color, font 수정 / global main 라벨 수정
  src/styles/global.ts
  src/styles/theme.ts
Labels: 💄 Style

#23 [Feature/#21] 검색페이지 퍼블리싱
  src/App.tsx
  src/assets/svgs/index.ts
  src/assets/svgs/mypotIcon.svg
  src/assets/svgs/saveIcon.svg
  src/assets/svgs/search.svg
  src/assets/svgs/setupIcon.svg
  src/assets/svgs/spotIcon.svg
  src/components/commons/SearchInput/SearchInput.style.ts
  src/components/commons/SearchInput/SearchInput.tsx
  src/components/index.ts
  src/components/layouts/Header/Header.style.ts
  src/constants/routes.ts
  src/pages/Search/Search.style.ts
  src/pages/Search/Search.tsx
  src/pages/SearchResult/SearchResult.style.ts
  src/pages/SearchResult/SearchResult.tsx
  src/pages/index.ts
  src/routes/router.tsx
Labels: 🌱 Add, ✨ Feat

#31 [Feature/#29] 팟 관련 버튼 UI 구현
  src/components/commons/Button/PotButton/PotButton.style.ts
  src/components/commons/Button/PotButton/PotButton.tsx
  src/components/index.ts
Labels: ✨ Feat

#26 [Refactor/#24] 따라다니는 Sidebar 구현
  src/App.tsx
  src/assets/svgs/pot.svg
  src/assets/svgs/profile.svg
  src/components/commons/SignUpButton/SignupButton.style.ts
  src/components/commons/SignUpButton/SignupButton.tsx
  src/components/index.ts
  src/components/layouts/SideBar/SideBar.style.ts
  src/components/layouts/SideBar/SideBar.tsx
Labels: ♻️ Refactor

#32 [Feature/#30] 모든 팟 페이지 구현
  src/components/layouts/SideBar/SideBar.tsx
  src/constants/routes.ts
  src/mocks/potCardsData.ts
  src/pages/Pot/Pot.tsx
  src/pages/Pots/AllPot/AllPotPage.style.ts
  src/pages/Pots/AllPot/AllPotPage.tsx
  src/pages/Pots/AppliedPot/AppliedPotPage.style.ts
  src/pages/Pots/AppliedPot/AppliedPotPage.tsx
  src/pages/Pots/MadePot/MadePotPage.style.ts
  src/pages/Pots/MadePot/MadePotPage.tsx
  src/pages/Pots/PotMain.style.ts
  src/pages/Pots/PotMain.tsx
  src/pages/index.ts
  src/routes/router.tsx
Labels: ✨ Feat

#35 [Refactor/#34] 버튼 UI 및 로직 수정
  src/components/commons/Badge/CategoryButton/CategoryButton.style.ts
  src/components/commons/Badge/CategoryButton/CategoryButton.tsx
  src/components/commons/Button/PotButton/PotButton.style.ts
  src/components/commons/Button/PotButton/PotButton.tsx
Labels: ♻️ Refactor

#37 [Feature/#36] Explain 공통 모달 UI 구현
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/index.ts
Labels: ✨ Feat

#39 [Feature/#38] 사이드바 푸터 전에 멈추게 하기
  src/components/layouts/SideBar/SideBar.tsx
Labels: ✨ Feat

#42 [Feature/#28] 팟 작성하기 페이지 퍼블리싱
  package.json
  src/App.tsx
  src/assets/svgs/homeIcon.svg
  src/assets/svgs/index.ts
  src/assets/svgs/myPot.svg
  src/assets/svgs/pot.svg
  src/components/layouts/SideBar/SideBar.style.ts
  src/components/layouts/SideBar/SideBar.tsx
  src/constants/routes.ts
  src/pages/CreatePot/CreatePot.style.ts
  src/pages/CreatePot/CreatePot.tsx
  src/pages/MyPot/MyPot.style.ts
  src/pages/index.ts
  src/routes/router.tsx
  yarn.lock
Labels: 🧹 Chore, ✨ Feat

#45 [Refactor/#43] 카테고리 버튼 및 버튼 리팩토링
  src/components/commons/Badge/CategoryButton/CategoryButton.style.ts
  src/components/commons/Badge/CategoryButton/CategoryButton.tsx
  src/components/commons/Button/Button.style.ts
  src/components/commons/Button/Button.tsx
  src/components/commons/PotButton/PotButton.style.ts
  src/components/commons/PotButton/PotButton.tsx
  src/components/commons/SignUpButton/SignupButton.style.ts
  src/components/commons/SignUpButton/SignupButton.tsx
  src/components/index.ts
  src/components/layouts/Header/Header.tsx
  src/pages/CreatePot/CreatePot.style.ts
  src/pages/CreatePot/CreatePot.tsx
  src/styles/theme.ts
Labels: ✨ Feat, ♻️ Refactor

#50 [Chore/#47] vercel.json 추가 및 GitHub Actions 워크플로우 설정
  .github/workflows/title.yml
  build.sh
  vercel.json
Labels: 🧹 Chore, 👷 CI

#33 [Feature/#20] 글쓰기 구현
  package.json
  src/assets/images/banner.png
  src/assets/images/index.ts
  src/assets/svgs/index.ts
  src/assets/svgs/pencil.svg
  src/assets/svgs/postbtnIcon.svg
  src/assets/svgs/pot.svg
  src/components/cards/PotCard/PotCard.tsx
  src/components/commons/Dropdown/Dropdown.style.ts
  src/components/commons/FloatingButton/FloatingButton.style.ts
  src/components/commons/FloatingButton/FloatingButton.tsx
  src/components/commons/TextField/TextField.tsx
  src/components/index.ts
  src/constants/routes.ts
  src/mocks/postCardsData.ts
  src/mocks/potCardsData.ts
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
  src/pages/WritePost/WritePost.style.ts
  src/pages/WritePost/WritePost.tsx
  src/pages/index.ts
  src/routes/router.tsx
  yarn.lock
Labels: 🧹 Chore, ✨ Feat

#44 [Feature/#27] 팟 상세페이지 퍼블리싱
  src/assets/svgs/arrowLeftRound.svg
  src/assets/svgs/check.svg
  src/assets/svgs/chevronLeft.svg
  src/assets/svgs/close.svg
  src/assets/svgs/closeIcon.svg
  src/assets/svgs/index.ts
  src/components/commons/Button/ArrowButton/ArrowButton.style.ts
  src/components/commons/Button/ArrowButton/ArrowButton.tsx
  src/components/commons/Button/CheckBox/CheckBox.style.ts
  src/components/commons/Button/CheckBox/CheckBox.tsx
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/commons/Modal/Modal.style.ts
  src/components/commons/Modal/Modal.tsx
  src/components/commons/PotButton/PotButton.style.ts
  src/components/index.ts
  src/constants/routes.ts
  src/mocks/memberListData.ts
  src/pages/PotDetail/PotDetail.style.ts
  src/pages/PotDetail/PotDetail.tsx
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.style.ts
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx
  src/pages/PotDetail/components/ApplyStackModal/ApplyStackModal.style.ts
  src/pages/PotDetail/components/ApplyStackModal/ApplyStackModal.tsx
  src/pages/PotDetail/components/MemberKakaoIdModal/MemberKakaoIdModal.style.ts
  src/pages/PotDetail/components/MemberKakaoIdModal/MemberKakaoIdModal.tsx
  src/pages/PotDetail/components/PotHeader/PotHeader.style.ts
  src/pages/PotDetail/components/PotHeader/PotHeader.tsx
  src/pages/PotDetail/components/PotInformation/PotInformation.style.ts
  src/pages/PotDetail/components/PotInformation/PotInformation.tsx
  src/pages/PotDetail/components/ProfileInformation/ProfileInformation.style.ts
  src/pages/PotDetail/components/ProfileInformation/ProfileInformation.tsx
  src/pages/PotDetail/components/ProfileModal/ProfileModal.style.ts
  src/pages/PotDetail/components/ProfileModal/ProfileModal.tsx
  src/pages/PotDetail/components/StartPotModal/StartPotModal.style.ts
  src/pages/PotDetail/components/StartPotModal/StartPotModal.tsx
  src/pages/PotDetail/components/index.ts
  src/pages/index.ts
  src/routes/router.tsx
  src/styles/theme.ts
  yarn.lock
Labels: ✨ Feat

#57 [Refactor/#46] 공통 모달창 수정 및 게시물 수정 드롭다운 제작
  package.json
  src/components/commons/Dropdown/MyFeedDropdown/MyFeedDropdown.style.ts
  src/components/commons/Dropdown/MyFeedDropdown/MyFeedDropdown.tsx
  src/components/commons/Modal/Modal.style.ts
  src/components/commons/Modal/Modal.tsx
  src/components/index.ts
  yarn.lock
Labels: ✨ Feat, ♻️ Refactor

#54 [Feature/#16] 회원가입 페이지
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/commons/TextField/TextField.style.ts
  src/components/commons/TextField/TextField.tsx
  src/constants/categories.ts
  src/constants/routes.ts
  src/pages/SignUp/SignUp.style.ts
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/components/CategorySelection.style.ts
  src/pages/SignUp/components/CategorySelection.tsx
  src/pages/SignUp/components/ContractDetailList.style.ts
  src/pages/SignUp/components/ContractDetailList.tsx
  src/pages/SignUp/components/ContractModal.style.ts
  src/pages/SignUp/components/ContractModal.tsx
  src/pages/SignUp/components/ContractsSection.style.ts
  src/pages/SignUp/components/ContractsSection.tsx
  src/pages/SignUp/components/NicknameInput.style.ts
  src/pages/SignUp/components/NicknameInput.tsx
  src/pages/SignUp/components/ProfileModal.style.ts
  src/pages/SignUp/components/ProfileModal.tsx
  src/pages/SignUp/components/Section.style.ts
  src/pages/SignUp/components/Section.tsx
  src/pages/SignUp/components/index.ts
  src/pages/index.ts
  src/routes/router.tsx
  src/styles/theme.ts
  yarn.lock
Labels: ✨ Feat

#67 [Feature/#63] API 유틸 추가
  .gitignore
  package.json
  src/App.tsx
  src/apis/apiUtils.ts
  src/apis/axiosInstance.ts
  src/apis/hooks/.gitkeep
  src/apis/tokenInstance.ts
  src/apis/types/response.ts
  src/constants/routes.ts
  src/pages/index.ts
  src/routes/router.tsx
  yarn.lock
Labels: ✨ Feat

#72 [Feature/#68] 랜딩페이지 퍼블리싱
  src/App.tsx
  src/assets/images/Mushroom.png
  src/assets/images/banner.png
  src/assets/images/banner.webp
  src/assets/images/broccoli.png
  src/assets/images/broccoli.webp
  src/assets/images/carrot.png
  src/assets/images/carrot.webp
  src/assets/images/index.ts
  src/assets/images/landingMyPot.webp
  src/assets/images/landingTask.webp
  src/assets/images/mushroom.webp
  src/assets/images/onion.png
  src/assets/images/onion.webp
  src/assets/svgs/expandMore.svg
  src/assets/svgs/index.ts
  src/components/commons/Button/Button.style.ts
  src/components/commons/Button/Button.tsx
  src/components/layouts/Header/Header.tsx
  src/mocks/memberListData.ts
  src/mocks/postCardsData.ts
  src/mocks/potCardsData.ts
  src/mocks/taskData.ts
  src/pages/CreatePot/CreatePot.tsx
  src/pages/Home/Home.tsx
  src/pages/Landing/Landing.style.ts
  src/pages/Landing/Landing.tsx
  src/pages/PotDetail/PotDetail.tsx
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx
  src/pages/PotDetail/components/PotHeader/PotHeader.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/WritePost/WritePost.tsx
  src/pages/index.ts
Labels: 🌱 Add, ✨ Feat, ♻️ Refactor

#58 [Feature/#56] 지원한 팟, 내가 만든 팟 페이지 구현
  src/assets/svgs/pot.svg
  src/components/commons/Modal/Modal.style.ts
  src/components/commons/Modal/Modal.tsx
  src/components/commons/PotButton/PotButton.tsx
  src/components/commons/PotInformation/PotInformation.style.ts
  src/components/commons/PotInformation/PotInformation.tsx
  src/components/index.ts
  src/mocks/appliedPotsData.ts
  src/mocks/onGoingPotsData.ts
  src/pages/PotDetail/PotDetail.tsx
  src/pages/PotDetail/components/index.ts
  src/pages/Pots/AppliedPot/AppliedPot.style.ts
  src/pages/Pots/AppliedPot/AppliedPot.tsx
  src/pages/Pots/AppliedPot/AppliedPotPage.style.ts
  src/pages/Pots/AppliedPot/AppliedPotPage.tsx
  src/pages/Pots/MadePot/MadePot.style.ts
  src/pages/Pots/MadePot/MadePot.tsx
  src/pages/Pots/MadePot/MadePotPage.style.ts
  src/pages/Pots/MadePot/MadePotPage.tsx
  src/pages/Pots/MadePot/components/FinishedPotCard.style.ts
  src/pages/Pots/MadePot/components/FinishedPotCard.tsx
  src/pages/Pots/MadePot/components/OnGoingPotCard.style.ts
  src/pages/Pots/MadePot/components/OnGoingPotCard.tsx
  src/pages/Pots/MadePot/components/Section.style.ts
  src/pages/Pots/MadePot/components/Section.tsx
  src/pages/Pots/MadePot/components/index.ts
  src/pages/Pots/components/PotInformationCard.style.ts
  src/pages/Pots/components/PotInformationCard.tsx
  src/pages/Pots/components/index.ts
  src/pages/index.ts
Labels: ✨ Feat
