Repository STACKPOT/STACKPOT-FE, pull requests merged in 2025-06, with the labels that each got.

#212 [Feature/#210] 피드 작성 바로가기 컴포넌트 구현
  src/components/cards/CtaCard/CtaCard.style.ts
  src/components/cards/CtaCard/CtaCard.tsx
  src/components/commons/Button/Button.style.ts
  src/components/commons/Button/Button.tsx
  src/components/index.ts
  src/pages/Home/Home.tsx
Labels: ✨ Feat

#214 [Feature/#213] 팟 카드 및 뱃지 UI 수정
  src/assets/svgs/icons/index.ts
  src/assets/svgs/icons/save.svg
  src/components/cards/PotCard/PotCard.style.ts
  src/components/cards/PotCard/PotCard.tsx
  src/components/commons/Badge/Badge.style.ts
  src/components/commons/Badge/Badge.tsx
Labels: 🌱 Add, ✨ Feat

#226 [Feature/#221] 설정페이지 화면 수정
  src/apis/types/user.ts
  src/components/commons/Button/PotButton/PotButton.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/pages/Setting/Setting.style.ts
  src/pages/Setting/Setting.tsx
  src/pages/Setting/components/CategorySelection.style.ts
  src/pages/Setting/components/CatetorySelection.tsx
  src/pages/Setting/components/RoleUpdate.style.ts
  src/pages/Setting/components/RoleUpdate.tsx
  src/pages/Setting/components/index.ts
Labels: ✨ Feat, 💄 Style

#225 [Feature/#220] 마이페이지 뷰 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/svgs/icons/add.svg
  src/assets/svgs/icons/index.ts
  src/assets/svgs/icons/searchBlue.svg
  src/assets/svgs/icons/setUp.svg
  src/components/cards/PostCard/PostCard.style.ts
  src/components/commons/TemperatureBar/TemperatureBar.style.ts
  src/constants/categories.ts
  src/mocks/handlers.ts
  src/pages/Home/components/Feed/Feed.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/components/MyPageContent/MyPageContent.style.ts
  src/pages/MyPage/components/MyPageContent/MyPageContent.tsx
  src/pages/MyPage/components/MyPageProfile/MyPageProfile.style.ts
  src/pages/MyPage/components/MyPageProfile/MyPageProfile.tsx
  yarn.lock
Labels: ✨ Feat

#222 [Feature/#216] 피드 댓글 구현 및 피드 상세 화면 수정
  src/assets/svgs/icons/plusButton.svg
  src/assets/svgs/icons/save.svg
  src/components/cards/CtaCard/CtaCard.tsx
  src/components/cards/FinishedPotCard/FinishedPotCard.tsx
  src/components/cards/OnGoingPotCard/OnGoingPotCard.tsx
  src/components/commons/Badge/Badge.tsx
  src/components/commons/Button/Button.style.ts
  src/components/commons/Button/Button.tsx
  src/components/commons/Button/PostButton/PostButton.style.ts
  src/components/commons/Button/PostButton/PostButton.tsx
  src/components/commons/Button/PotButton/PotButton.style.ts
  src/components/commons/Button/PotButton/PotButton.tsx
  src/components/commons/Comment/Comment.style.ts
  src/components/commons/Comment/Comment.tsx
  src/components/commons/Comment/CommentSection.style.ts
  src/components/commons/Comment/CommentSection.tsx
  src/components/commons/Comment/CommentWriter.style.ts
  src/components/commons/Comment/CommentWriter.tsx
  src/components/index.ts
  src/components/layouts/Header/Header.tsx
  src/mocks/commentData.ts
  src/pages/CreatePot/components/FormHeader/FormHeader.tsx
  src/pages/EditFinishedPot/components/FinishedPotForm.tsx
  src/pages/EditPost/EditPost.tsx
  src/pages/FeedDetail/FeedDetail.style.ts
  src/pages/FeedDetail/FeedDetail.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/PotDetail/components/PotHeader/PotHeader.tsx
  src/pages/Pots/pages/AppliedPot/components/PotInformationCard.tsx
  src/pages/Setting/Setting.tsx
  src/pages/SignUp/SignUp.tsx
  yarn.lock
Labels: ✨ Feat, ♻️ Refactor

#228 [Feature/#227] 모달 수정 및 로그인 모달 구현
  src/assets/svgs/icons/close.svg
  src/assets/svgs/social/google.svg
  src/assets/svgs/social/index.ts
  src/assets/svgs/social/kakaoTalk.svg
  src/assets/svgs/social/naver.svg
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/commons/Modal/LoginModal/LoginModal.style.ts
  src/components/commons/Modal/LoginModal/LoginModal.tsx
  src/components/commons/Modal/Modal.style.ts
  src/components/commons/Modal/Modal.tsx
  src/components/layouts/Header/Header.tsx
  src/styles/media.ts
  src/styles/theme.ts
Labels: ✨ Feat, ♻️ Refactor
