Repository STACKPOT/STACKPOT-FE, pull requests merged in 2025-02, with the labels that each got.

#77 [Feature/#73] 카카오 api 연결
  src/App.tsx
  src/apis/hooks/.gitkeep
  src/apis/hooks/users/useGetSignIn.ts
  src/apis/types/user.ts
  src/apis/userAPI.ts
  src/assets/images/broccoli.webp
  src/assets/images/carrot.webp
  src/assets/images/mushroom.webp
  src/assets/images/onion.webp
  src/components/layouts/Header/Header.tsx
  src/pages/Callback/Callback.tsx
  src/pages/Landing/Landing.style.ts
  src/pages/index.ts
  src/routes/router.tsx
Labels: ✨ Feat

#82 [Feature/#75] 404 페이지 퍼블리싱
  src/assets/images/404.webp
  src/assets/images/index.ts
  src/assets/svgs/search.svg
  src/components/commons/Button/Button.style.ts
  src/components/commons/Button/Button.tsx
  src/components/commons/SearchInput/SearchInput.style.ts
  src/components/commons/SearchInput/SearchInput.tsx
  src/components/layouts/Header/Header.style.ts
  src/components/layouts/Header/Header.tsx
  src/pages/NotFound/NotFound.style.ts
  src/pages/NotFound/NotFound.tsx
Labels: 🌱 Add, ✨ Feat

#76 [Feature/#69] 마이페이지 구현
  src/assets/svgs/angularClose.svg
  src/assets/svgs/index.ts
  src/assets/svgs/info.svg
  src/assets/svgs/pin.svg
  src/assets/svgs/pot.svg
  src/components/cards/FinishedPotCard/FinishedPotCard.style.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.tsx
  src/components/commons/TemperatureBar/TemperatureBar.style.ts
  src/components/commons/TemperatureBar/TemperatureBar.tsx
  src/components/index.ts
  src/components/layouts/SideBar/SideBar.style.ts
  src/components/layouts/SideBar/SideBar.tsx
  src/components/layouts/SideBarProfileModal/SideBarProfileModal.style.ts
  src/components/layouts/SideBarProfileModal/SideBarProfileModal.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/components/MyPageProfile.style.ts
  src/pages/MyPage/components/MyPageProfile.tsx
  src/pages/MyPage/components/index.ts
  src/pages/Pots/MadePot/MadePot.tsx
  src/pages/Pots/MadePot/components/index.ts
Labels: ✨ Feat

#78 [Refactor/#70] 카드 컴포넌트 리팩토링
  src/components/cards/PostCard/PostCard.style.ts
  src/components/cards/PostCard/PostCard.tsx
  src/components/cards/PotCard/PotCard.style.ts
  src/components/cards/PotCard/PotCard.tsx
  src/mocks/postCardsData.ts
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.style.ts
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx
  src/pages/PotDetail/components/MemberKakaoIdModal/MemberKakaoIdModal.tsx
  src/pages/PotDetail/components/ProfileInformation/ProfileInformation.tsx
  src/pages/PotDetail/components/ProfileModal/ProfileModal.tsx
  src/pages/PotDetail/components/StartPotModal/StartPotModal.tsx
  src/pages/Pots/components/PotInformationCard.tsx
Labels: ♻️ Refactor

#81 [Refactor/#80] 회원가입 텍스트필드 및 기타 컴포넌트 수정
  src/components/commons/Badge/MemberGroup/MemberGroup.tsx
  src/components/commons/PotInformation/PotInformation.tsx
  src/components/commons/TextField/TextField.style.ts
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx
  src/pages/Pots/AppliedPot/AppliedPot.tsx
  src/pages/Pots/MadePot/MadePot.tsx
  src/pages/SignUp/components/CategorySelection.tsx
  src/pages/SignUp/components/ContractsSection.style.ts
  src/pages/SignUp/components/ContractsSection.tsx
  src/pages/SignUp/components/NicknameInput.style.ts
Labels: ♻️ Refactor

#88 [Feature/#83] home 페이지 api 연결
  biome.json
  index.html
  package.json
  public/favicon.svg
  src/apis/feedAPI.ts
  src/apis/hooks/feeds/useGetFeeds.ts
  src/apis/hooks/pots/useGetPots.ts
  src/apis/hooks/users/useGetSignIn.ts
  src/apis/potAPI.ts
  src/apis/types/feed.ts
  src/apis/types/pot.ts
  src/apis/userAPI.ts
  src/assets/images/index.ts
  src/assets/svgs/index.ts
  src/assets/svgs/left.svg
  src/components/cards/PostCard/PostCard.tsx
  src/components/cards/PotCard/PotCard.tsx
  src/components/commons/Badge/CategoryButton/CategoryButton.tsx
  src/components/commons/Badge/DdayBadge/DdayBadge.tsx
  src/components/layouts/Header/Header.tsx
  src/constants/categories.ts
  src/constants/roleImage.ts
  src/mocks/onGoingPotsData.ts
  src/mocks/taskCardData.ts
  src/mocks/taskData.ts
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/Feed/Feed.style.ts
  src/pages/Home/components/Feed/Feed.tsx
  src/pages/Home/components/PopularPots/PopularPots.style.ts
  src/pages/Home/components/PopularPots/PopularPots.tsx
  src/pages/Landing/Landing.tsx
  src/types/.gitkeep
  yarn.lock
Labels: 🧹 Chore, ✨ Feat, ♻️ Refactor

#87 [Refactor/#86] 진행중인 팟 카드 수정
  src/components/cards/OnGoingPotCard/OnGoingPotCard.style.ts
  src/components/cards/OnGoingPotCard/OnGoingPotCard.tsx
  src/components/index.ts
  src/pages/Pots/MadePot/MadePot.tsx
  src/pages/Pots/MadePot/components/index.ts
Labels: ♻️ Refactor

#92 [Feature/#90] 무한스크롤 구현
  src/apis/hooks/feeds/useGetFeeds.ts
  src/apis/types/feed.ts
  src/assets/svgs/index.ts
  src/assets/svgs/loadingSpinner.svg
  src/components/cards/PostCard/PostCard.style.ts
  src/components/cards/PotCard/PotCard.style.ts
  src/pages/Home/components/Feed/Feed.style.ts
  src/pages/Home/components/Feed/Feed.tsx
  src/pages/Home/components/PopularPots/PopularPots.tsx
Labels: 🐛 Fix, 🌱 Add, ✨ Feat, ♻️ Refactor

#64 [Feature/#60] 설정 페이지 구현
  src/components/commons/Dropdown/MyFeedDropdown/MyFeedDropdown.style.ts
  src/components/commons/Dropdown/MyFeedDropdown/MyFeedDropdown.tsx
  src/components/commons/Modal/Modal.style.ts
  src/pages/Setting/Setting.style.ts
  src/pages/Setting/Setting.tsx
  src/styles/global.ts
Labels: ✨ Feat, ♻️ Refactor

#74 [Feature/#71] 나의 팟 첫 페이지 구현
  src/components/cards/OnGoingPotCard/OnGoingPotCard.tsx
  src/components/layouts/SideBar/SideBar.tsx
  src/constants/routes.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPot/MyPot.style.ts
  src/pages/MyPot/MyPot.tsx
  src/pages/index.ts
  src/routes/router.tsx
  src/styles/theme.ts
Labels: ✨ Feat

#97 [Feature/#89] 회원가입 api 연결
  .gitignore
  .npmrc
  index.html
  package.json
  public/favicon.png
  src/apis/hooks/users/useGetNickname.ts
  src/apis/hooks/users/usePatchSignIn.ts
  src/apis/hooks/users/usePostNickname.ts
  src/apis/types/feed.ts
  src/apis/types/pot.ts
  src/apis/types/user.ts
  src/apis/userAPI.ts
  src/assets/svgs/index.ts
  src/assets/svgs/profile.svg
  src/components/cards/.gitkeep
  src/components/cards/PostCard/PostCard.tsx
  src/components/cards/PotCard/PotCard.tsx
  src/components/commons/Button/Button.style.ts
  src/components/commons/Button/Button.tsx
  src/components/commons/Button/CheckBox/CheckBox.tsx
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/commons/TextField/TextField.style.ts
  src/components/layouts/Header/Header.style.ts
  src/components/layouts/Header/Header.tsx
  src/components/layouts/SideBar/SideBar.style.ts
  src/components/layouts/SideBar/SideBar.tsx
  src/constants/categories.ts
  src/constants/roleImage.ts
  src/pages/MyPot/MyPotCalendar/components/TaskBox/TaskBox.tsx
  src/pages/SignUp/SignUp.style.ts
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/components/CategorySelection.tsx
  src/pages/SignUp/components/CategorySelection/CategorySelection.style.ts
  src/pages/SignUp/components/CategorySelection/CategorySelection.tsx
  src/pages/SignUp/components/ContractDetailList.tsx
  src/pages/SignUp/components/ContractModal.tsx
  src/pages/SignUp/components/ContractModal/ContractModal.style.ts
  src/pages/SignUp/components/ContractModal/ContractModal.tsx
  src/pages/SignUp/components/ContractionDetailList/ContractDetailList.style.ts
  src/pages/SignUp/components/ContractionDetailList/ContractDetailList.tsx
  src/pages/SignUp/components/ContractsSection.style.ts
  src/pages/SignUp/components/ContractsSection.tsx
  src/pages/SignUp/components/ContractsSection/ContractsSection.style.ts
  src/pages/SignUp/components/ContractsSection/ContractsSection.tsx
  src/pages/SignUp/components/NicknameInput.style.ts
  src/pages/SignUp/components/NicknameInput.tsx
  src/pages/SignUp/components/ProfileModal.style.ts
  src/pages/SignUp/components/ProfileModal.tsx
  src/pages/SignUp/components/ProfileModal/ProfileModal.style.ts
  src/pages/SignUp/components/ProfileModal/ProfileModal.tsx
  src/pages/SignUp/components/Section.style.ts
  src/pages/SignUp/components/Section.tsx
  src/pages/SignUp/components/Section/Section.style.ts
  src/pages/SignUp/components/Section/Section.tsx
  src/pages/SignUp/components/index.ts
  src/pages/feeds/.gitkeep
  src/types/role.ts
  yarn.lock
Labels: 🌱 Add, 🧹 Chore, ✨ Feat, ♻️ Refactor, 💄 Style

#101 [Fix/#100] 회원가입 로직 수정
  .gitignore
  src/apis/hooks/users/useGetSignIn.ts
  src/pages/Callback/Callback.style.ts
  src/pages/Callback/Callback.tsx
Labels: 🐛 Fix, 🧹 Chore, ✨ Feat

#94 [Feature/#79] 끓인 팟 수정하기 및 게시글 수정하기 페이지 구현
  src/assets/svgs/appeal.svg
  src/assets/svgs/book.svg
  src/assets/svgs/create.svg
  src/assets/svgs/index.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.style.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.tsx
  src/components/commons/InformationPopper/InformationPopper.style.ts
  src/components/commons/InformationPopper/InformationPopper.tsx
  src/components/commons/PartRecruitment/PartRecruitment.style.ts
  src/components/commons/PartRecruitment/PartRecruitment.tsx
  src/components/commons/PotButton/PotButton.style.ts
  src/components/commons/PotButton/PotButton.tsx
  src/components/commons/TemperatureBar/TemperatureBar.style.ts
  src/components/commons/TemperatureBar/TemperatureBar.tsx
  src/components/index.ts
  src/constants/routes.ts
  src/mocks/finishedPotsData.ts
  src/pages/CreateFinishedPot/CreateFinishedPot.tsx
  src/pages/EditFinishedPot/EditFinishedPot.style.ts
  src/pages/EditFinishedPot/EditFinishedPot.tsx
  src/pages/EditFinishedPot/components/EditFinishedPotForm.style.ts
  src/pages/EditFinishedPot/components/EditFinishedPotForm.tsx
  src/pages/EditFinishedPot/components/index.ts
  src/pages/EditPost/EditPost.style.ts
  src/pages/EditPost/EditPost.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/components/AppealModal.style.ts
  src/pages/MyPage/components/AppealModal.tsx
  src/pages/MyPage/components/PotSummaryModal.style.ts
  src/pages/MyPage/components/PotSummaryModal.tsx
  src/pages/MyPage/components/index.ts
  src/pages/Pots/MadePot/MadePot.tsx
  src/pages/UserPage/UserPage.style.ts
  src/pages/UserPage/UserPage.tsx
  src/pages/UserPage/components/UserPageProfile.style.ts
  src/pages/UserPage/components/UserPageProfile.tsx
  src/pages/UserPage/components/index.ts
  src/pages/index.ts
  src/routes/router.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: ✨ Feat, ♻️ Refactor

#93 [Feature/#91] 나의 팟 페이지 todo api GET, PATCH 연결
  src/apis/hooks/myPots/useGetMyPotTodo.ts
  src/apis/hooks/myPots/usePatchMyTodo.ts
  src/apis/myPotAPI.ts
  src/apis/types/todo.ts
  src/components/cards/TaskCard/TaskCard.style.ts
  src/pages/MyPot/MyPotMain.tsx
  src/pages/MyPot/MyPotStatus/AboutWorkModal/AboutWorkModal.tsx
  src/pages/MyPot/MyPotStatus/MyPotStatus.tsx
  src/pages/MyPot/MyPotStatus/MyTodoModal/MyTodoModal.style.ts
  src/pages/MyPot/MyPotStatus/MyTodoModal/MyTodoModal.tsx
  src/pages/MyPot/components/MyPotStatusHeader/MyPotStatusHeader.tsx
  src/pages/MyPot/components/MyPotTodoCard/MyPotTodoCard.style.ts
  src/pages/MyPot/components/MyPotTodoCard/MyPotTodoCard.tsx
  src/pages/MyPot/components/MyPotTodoList/MyPotTodoList.tsx
  src/pages/MyPot/components/MyTodoModalWrapper/MyTodoModalWrapper.tsx
  src/pages/MyPot/components/index.ts
  src/types/taskStatus.ts
Labels: ✨ Feat

#95 [Feature/#85] 팟 생성 및 팟 상세 페이지 api 연결
  src/apis/hooks/pots/useApplyPot.ts
  src/apis/hooks/pots/useCancelApply.ts
  src/apis/hooks/pots/useCreatePot.ts
  src/apis/hooks/pots/useGetPotApplicants.ts
  src/apis/hooks/pots/useGetPotDetail.ts
  src/apis/hooks/pots/useGetPotMembers.ts
  src/apis/hooks/pots/useStartPot.ts
  src/apis/hooks/users/useGetMyProfile.ts
  src/apis/potAPI.ts
  src/apis/types/pot.ts
  src/apis/types/user.ts
  src/apis/userAPI.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/commons/PartRecruitment/PartRecruitment.style.ts
  src/components/commons/PartRecruitment/PartRecruitment.tsx
  src/constants/categories.ts
  src/pages/CreatePot/CreatePot.style.ts
  src/pages/CreatePot/CreatePot.tsx
  src/pages/CreatePot/components/DatePicker/DatePicker.tsx
  src/pages/EditFinishedPot/components/EditFinishedPotForm.style.ts
  src/pages/EditFinishedPot/components/EditFinishedPotForm.tsx
  src/pages/PotDetail/PotDetail.style.ts
  src/pages/PotDetail/PotDetail.tsx
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.style.ts
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx
  src/pages/PotDetail/components/MemberKakaoIdModal/MemberKakaoIdModal.tsx
  src/pages/PotDetail/components/PotHeader/PotHeader.tsx
  src/pages/PotDetail/components/ProfileInformation/ProfileInformation.tsx
  src/pages/PotDetail/components/ProfileModal/ProfileModal.tsx
  src/pages/PotDetail/components/StartPotModal/StartPotModal.tsx
  src/types/participation.ts
  src/types/potStatus.ts
Labels: ✨ Feat

#96 [Feature/#84] 끓인 팟 상세보기, 마이페이지 api 연동
  src/apis/finishedmodalAPI.ts
  src/apis/hooks/mypage/useGetFinishedModal.ts
  src/apis/hooks/mypage/useGetMyPage.ts
  src/apis/mypageAPI.ts
  src/apis/types/finishedmodal.ts
  src/apis/types/mypage.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.tsx
  src/components/cards/OnGoingPotCard/OnGoingPotCard.tsx
  src/components/cards/PostCard/PostCard.tsx
  src/mocks/appliedPotsData.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/components/MyPageProfile.tsx
  src/pages/MyPage/components/PotSummaryModal.tsx
  src/pages/PotDetail/PotDetail.tsx
  src/pages/Pots/MadePot/MadePot.tsx
  src/pages/Pots/components/PotInformationCard.tsx
  src/pages/WritePost/WritePost.style.ts
  src/pages/WritePost/WritePost.tsx
Labels: ✨ Feat

#104 [Feature/#103] Todo완료 API 연결
  src/apis/hooks/myPots/useGetMyPotTodo.ts
  src/apis/hooks/myPots/usePatchMyTodo.ts
  src/apis/hooks/myPots/usePatchMyTodoStatus.ts
  src/apis/myPotAPI.ts
  src/apis/types/myPot.ts
  src/components/commons/Button/CheckBox/CheckBox.style.ts
  src/pages/MyPot/components/MyPotTodoCard/MyPotTodoCard.tsx
Labels: ✨ Feat

#108 [Feature/#106] 검색 페이지 api 연결
  package.json
  src/apis/ searchAPI.ts
  src/apis/hooks/searches/useGetSearch.ts
  src/apis/types/search.ts
  src/components/commons/SearchInput/SearchInput.tsx
  src/constants/categories.ts
  src/pages/Pots/PotMain.style.ts
  src/pages/Search/Search.tsx
  src/pages/SearchResult/SearchResult.style.ts
  src/pages/SearchResult/SearchResult.tsx
  yarn.lock
Labels: ✨ Feat, ♻️ Refactor

#110 [Feature/#109] 나의 팟 첫 페이지 api 연결 및 라우팅 방식 변경
  src/apis/hooks/myPots/useGetMyPot.ts
  src/apis/hooks/searches/useGetSearch.ts
  src/apis/myPotAPI.ts
  src/apis/searchAPI.ts
  src/apis/types/myPot.ts
  src/components/cards/OnGoingPotCard/OnGoingPotCard.tsx
  src/components/commons/Badge/MemberGroup/MemberGroup.tsx
  src/constants/routes.ts
  src/pages/MyPot/MyPot.style.ts
  src/pages/MyPot/MyPot.tsx
  src/pages/MyPot/MyPotMain.tsx
  src/pages/MyPot/MyPotStatus/MyPotStatus.tsx
  src/routes/router.tsx
Labels: ✨ Feat, ♻️ Refactor

#112 [Feature/#111] 모든 팟 페이지 api 연결
  public/favicon.svg
  src/apis/hooks/pots/useGetPots.ts
  src/apis/potAPI.ts
  src/apis/types/pot.ts
  src/pages/Home/components/PopularPots/PopularPots.tsx
  src/pages/Pots/AllPot/AllPotPage.style.ts
  src/pages/Pots/AllPot/AllPotPage.tsx
  src/pages/Pots/AllPot/components/CategoryButton.style.ts
  src/pages/Pots/AllPot/components/CategoryButton.tsx
Labels: ✨ Feat, ♻️ Refactor

#125 [BugFix/#124] 회원가입 오류 수정
  src/apis/userAPI.ts
  src/pages/SignUp/SignUp.tsx
Labels: 🐛 Fix

#123 [Feature/#118] 토큰 재발급 및 로그아웃 api 연결
  package.json
  src/apis/hooks/users/useGetNickname.ts
  src/apis/hooks/users/useGetSignIn.ts
  src/apis/hooks/users/userPostLogout.ts
  src/apis/tokenAPI.ts
  src/apis/tokenInstance.ts
  src/apis/types/token.ts
  src/apis/types/user.ts
  src/apis/userAPI.ts
  src/assets/images/index.ts
  src/assets/images/profile.webp
  src/assets/svgs/arrowDropdown.svg
  src/assets/svgs/index.ts
  src/assets/svgs/profile.svg
  src/components/layouts/Header/Header.style.ts
  src/components/layouts/Header/Header.tsx
  src/constants/profileRole.ts
  src/constants/roleImage.ts
  src/pages/MyPot/MyPotCalendar/components/TaskBox/TaskBox.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/components/ProfileModal/ProfileModal.tsx
  src/stores/useAuthStore.ts
  src/types/role.ts
  yarn.lock
Labels: 🌱 Add, ✨ Feat, ♻️ Refactor

#120 [Feature/#119] 프로필 수정 api 연동
  src/apis/hooks/users/usePatchUserProfileUpdate.ts
  src/apis/types/user.ts
  src/apis/userAPI.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/commons/Modal/Modal.style.ts
  src/pages/Setting/Setting.style.ts
  src/pages/Setting/Setting.tsx
  src/pages/Setting/components/CategorySelection.style.ts
  src/pages/Setting/components/CatetorySelection.tsx
  src/pages/Setting/components/index.ts
Labels: ✨ Feat

#131 [Bugfix/#130] 팟 이동 오류 수정
  src/apis/types/feed.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.tsx
  src/components/cards/PostCard/PostCard.style.ts
  src/components/cards/PostCard/PostCard.tsx
  src/components/cards/PotCard/PotCard.style.ts
  src/components/cards/PotCard/PotCard.tsx
  src/constants/routes.ts
  src/pages/EditPot/EditPot.tsx
  src/pages/Home/components/Feed/Feed.tsx
  src/pages/Home/components/PopularPots/PopularPots.tsx
  src/pages/Pots/AllPot/AllPotPage.tsx
  src/routes/router.tsx
Labels: 🐛 Fix, ✨ Feat, ♻️ Refactor

#133 [Bugfix/#132] 닉네임 생성 response 오류 수정
  src/pages/SignUp/components/ProfileModal/ProfileModal.tsx
  src/pages/UserPage/components/UserPageProfile.tsx
Labels: 🐛 Fix, ♻️ Refactor

#136 [Featuere/#134] 회원 탈퇴 api 연결
  src/apis/apiUtils.ts
  src/apis/hooks/users/useDeleteUser.ts
  src/apis/userAPI.ts
  src/pages/PotDetail/PotDetail.tsx
  src/pages/Setting/Setting.tsx
Labels: ✨ Feat

#127 [Feature/#126] 피드 좋아요 api 연결
  src/apis/feedAPI.ts
  src/apis/hooks/feeds/usePostFeedLike.ts
  src/apis/types/mypage.ts
  src/apis/types/search.ts
  src/components/cards/PostCard/PostCard.style.ts
  src/components/cards/PostCard/PostCard.tsx
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/pages/Setting/Setting.tsx
Labels: ✨ Feat

#116 [Feature/#105] 피드 작성 및 수정 api 연동
  src/apis/feedAPI.ts
  src/apis/finishedmodalAPI.ts
  src/apis/hooks/feeds/useGetFeedDetail.ts
  src/apis/hooks/feeds/useGetFeedDetails.ts
  src/apis/hooks/feeds/usePatchFeed.ts
  src/apis/hooks/feeds/usePostFeed.ts
  src/apis/hooks/users/useGetFinishedModal.ts
  src/apis/hooks/users/useGetMyPage.ts
  src/apis/mypageAPI.ts
  src/apis/types/feed.ts
  src/apis/types/finishedmodal.ts
  src/apis/types/mypage.ts
  src/apis/types/user.ts
  src/apis/userAPI.ts
  src/components/cards/PostCard/PostCard.tsx
  src/components/commons/Dropdown/Dropdown.tsx
  src/components/commons/Dropdown/MyFeedDropdown/MyFeedDropdown.style.ts
  src/components/commons/PostFoam/PostFoam.style.ts
  src/components/commons/PostFoam/PostFoam.tsx
  src/components/index.ts
  src/constants/routes.ts
  src/pages/EditPost/EditPost.style.ts
  src/pages/EditPost/EditPost.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/components/MyPageProfile.tsx
  src/pages/MyPage/components/PotSummaryModal.tsx
  src/pages/WritePost/WritePost.tsx
  src/routes/router.tsx
Labels: ✨ Feat

#129 [Feature/#128] 팟 끓이기 api 연결
  src/apis/hooks/pots/useApplyPot.ts
  src/apis/hooks/pots/useCancelApply.ts
  src/apis/hooks/pots/useCreatePot.ts
  src/apis/hooks/pots/useGetPotDetail.ts
  src/apis/hooks/pots/useGetPotSummary.ts
  src/apis/hooks/pots/usePatchPotComplete.ts
  src/apis/hooks/pots/useStartPot.ts
  src/apis/potAPI.ts
  src/apis/types/pot.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.tsx
  src/components/cards/OnGoingPotCard/OnGoingPotCard.tsx
  src/pages/CreateFinishedPot/CreateFinishedPot.tsx
  src/pages/CreatePot/CreatePot.style.ts
  src/pages/CreatePot/CreatePot.tsx
  src/pages/CreatePot/components/PotForm.tsx
  src/pages/EditFinishedPot/EditFinishedPot.tsx
  src/pages/EditFinishedPot/components/EditFinishedPotForm.tsx
  src/pages/EditFinishedPot/components/FinishedPotForm.style.ts
  src/pages/EditFinishedPot/components/FinishedPotForm.tsx
  src/pages/EditFinishedPot/components/SummaryLoadingModal.style.ts
  src/pages/EditFinishedPot/components/SummaryLoadingModal.tsx
  src/pages/EditFinishedPot/components/index.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/PotDetail/PotDetail.tsx
  src/pages/PotDetail/components/MemberKakaoIdModal/MemberKakaoIdModal.tsx
  src/pages/PotDetail/components/PotHeader/PotHeader.tsx
  src/pages/PotDetail/components/StartPotModal/StartPotModal.tsx
  src/pages/Pots/MadePot/MadePot.tsx
  src/pages/Pots/MadePot/components/RecruitingMyPotCard.tsx
  src/pages/Pots/components/PotInformationCard.tsx
  src/pages/UserPage/UserPage.tsx
  src/routes/router.tsx
Labels: ✨ Feat

#122 [Feature/#107] MyPot페이지 task 조회, 상세조회, 삭제, 수정 api 연결
  src/apis/hooks/myPots/useDeleteMyPotTask.ts
  src/apis/hooks/myPots/useGetMyPotTask.ts
  src/apis/hooks/myPots/useGetMyPotTaskDetail.ts
  src/apis/hooks/myPots/useGetMyPotTodo.ts
  src/apis/hooks/myPots/usePatchMyPotTask.tsx
  src/apis/hooks/myPots/usePatchMyPotTodo.ts
  src/apis/hooks/myPots/usePatchMyPotTodoStatus.ts
  src/apis/myPotAPI.ts
  src/apis/types/myPot.ts
  src/components/cards/TaskCard/TaskCard.style.ts
  src/components/cards/TaskCard/TaskCard.tsx
  src/components/commons/Dropdown/MyFeedDropdown/MyFeedDropdown.style.ts
  src/constants/categories.ts
  src/constants/routes.ts
  src/pages/MyPot/MyPotMain.style.ts
  src/pages/MyPot/MyPotMain.tsx
  src/pages/MyPot/MyPotStatus/AboutWorkModal/AboutWorkModal.style.ts
  src/pages/MyPot/MyPotStatus/AboutWorkModal/AboutWorkModal.tsx
  src/pages/MyPot/MyPotStatus/MyPotStatus.style.ts
  src/pages/MyPot/MyPotStatus/MyPotStatus.tsx
  src/pages/MyPot/MyPotStatus/MyTodoModal/MyTodoModal.tsx
  src/pages/MyPot/MyPotStatus/TaskDetail/TaskDetail.style.ts
  src/pages/MyPot/MyPotStatus/TaskDetail/TaskDetail.tsx
  src/pages/MyPot/components/AboutWorkModalWrapper/AboutworkModalWrapper.tsx
  src/pages/MyPot/components/ActionButton/ActionButton.tsx
  src/pages/MyPot/components/ConfirmModalWrapper/ConfirmModalWrapper.style.ts
  src/pages/MyPot/components/ConfirmModalWrapper/ConfirmModalWrapper.tsx
  src/pages/MyPot/components/DateInput/DateInput.tsx
  src/pages/MyPot/components/ExplainationInputField/ExplainationInputField.tsx
  src/pages/MyPot/components/Loading/Loading.tsx
  src/pages/MyPot/components/MyPotTodoCard/MyPotTodoCard.tsx
  src/pages/MyPot/components/MyPotTodoList/MyPotTodoList.tsx
  src/pages/MyPot/components/StateBadgeSelect/StateBadgeSelect.style.ts
  src/pages/MyPot/components/StateBadgeSelect/StateBadgeSelect.tsx
  src/pages/MyPot/components/Statusboard/StatusBoard.tsx
  src/pages/MyPot/components/TaskCardList/TaskCardList.tsx
  src/pages/MyPot/components/TextInput/TextInput.tsx
  src/pages/MyPot/components/TodoStatusSection/TodoStatusSection.tsx
  src/pages/MyPot/components/index.ts
  src/routes/router.tsx
  src/types/taskStatus.ts
Labels: ✨ Feat

#142 [Feature/#141] 배너 구현 및 헤더 스타일 수정
  src/assets/images/banner.webp
  src/assets/svgs/arrowDropdown.svg
  src/assets/svgs/index.ts
  src/assets/svgs/logo.svg
  src/assets/svgs/right.svg
  src/components/commons/Button/Button.tsx
  src/components/layouts/Header/Header.style.ts
  src/components/layouts/Header/Header.tsx
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
  src/styles/theme.ts
Labels: ✨ Feat, ♻️ Refactor, 💄 Style

#145 [Feature/#143] 스낵바로 toast 기능 구현
  package.json
  src/App.tsx
  src/apis/hooks/users/usePostNickname.ts
  src/apis/hooks/users/userPostLogout.ts
  src/providers/SnackbarProvider.tsx
  src/providers/index.ts
  yarn.lock
Labels: ✨ Feat

#138 [Feature/#137] 사용자별 마이페이지 조회 API, 사용자별 정보 조회 API 연동
  src/apis/hooks/users/useGetFinishedModal.ts
  src/apis/hooks/users/useGetMyPage.ts
  src/apis/hooks/users/useGetUsersInfo.ts
  src/apis/hooks/users/useGetUsersMyPages.ts
  src/apis/types/user.ts
  src/apis/userAPI.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/UserPage/UserPage.tsx
  src/pages/UserPage/components/UserPageProfile.tsx
  src/routes/router.tsx
Labels: ✨ Feat

#147 [Bugfix/#146] 닉네임 오류 수정
  src/apis/hooks/users/userPostLogout.ts
Labels: 🐛 Fix

#151 [Refactor/#140] 모달 리팩토링
  src/apis/potAPI.ts
  src/apis/types/pot.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/commons/Modal/Modal.style.ts
  src/pages/EditFinishedPot/components/SummaryLoadingModal.style.ts
  src/pages/PotDetail/components/ApplyModal/ApplyModal.style.ts
  src/pages/PotDetail/components/ApplyModal/ApplyModal.tsx
  src/pages/PotDetail/components/ApplyProfileModal/ApplyProfileModal.style.ts
  src/pages/PotDetail/components/ApplyProfileModal/ApplyProfileModal.tsx
  src/pages/PotDetail/components/ApplyStackModal/ApplyStackModal.tsx
  src/pages/PotDetail/components/PotHeader/PotHeader.tsx
  src/pages/PotDetail/components/ProfileModal/ProfileModal.style.ts
  src/pages/PotDetail/components/ProfileModal/ProfileModal.tsx
  src/pages/PotDetail/components/index.ts
Labels: ♻️ Refactor

#152 [Feature/#148] 랜딩 페이지 내용 추가 및 애니매이션 구현
  src/assets/images/index.ts
  src/assets/images/landingAISummary.webp
  src/assets/images/landingFeed.webp
  src/assets/images/landingFinishedPot.webp
  src/assets/images/landingModal.webp
  src/assets/images/landingMyPage.webp
  src/assets/images/landingPot.webp
  src/assets/images/landingPotDetail.webp
  src/assets/images/landingProfile.webp
  src/assets/images/landingTaskBoard.webp
  src/assets/images/landingTaskCard.webp
  src/constants/landing.ts
  src/pages/Landing/Landing.style.ts
  src/pages/Landing/Landing.tsx
  src/pages/Landing/components/Step1/Step1.style.ts
  src/pages/Landing/components/Step1/Step1.tsx
  src/pages/Landing/components/Step2/Step2.style.ts
  src/pages/Landing/components/Step2/Step2.tsx
  src/pages/Landing/components/Step3/Step3.style.ts
  src/pages/Landing/components/Step3/Step3.tsx
  src/pages/Landing/components/Step4/Step4.style.ts
  src/pages/Landing/components/Step4/Step4.tsx
Labels: ✨ Feat, ♻️ Refactor, 💄 Style

#153 [Feature/#144] 팟 멤버 조회 api, 소유자 api 연결
  package.json
  src/apis/hooks/myPots/useGetMyPotMemeber.ts
  src/apis/hooks/myPots/useGetMyPotOwner.ts
  src/apis/myPotAPI.ts
  src/apis/types/myPot.ts
  src/pages/MyPot/MyPotMain.style.ts
  src/pages/MyPot/MyPotMain.tsx
  src/pages/MyPot/MyPotStatus/MyPotStatus.style.ts
  src/pages/MyPot/components/ContributorList/ContributorList.style.ts
  src/pages/MyPot/components/ContributorList/ContributorList.tsx
  src/pages/MyPot/components/MemberIdModal/MemberIdModal.style.ts
  src/pages/MyPot/components/MemberIdModal/MemberIdModal.tsx
  src/pages/MyPot/components/MemberIdModalWrapper/MemberIdModalWrapper.tsx
  src/pages/MyPot/components/MyPotStatusHeader/MyPotStatusHeader.tsx
  src/pages/MyPot/components/index.ts
  yarn.lock
Labels: ✨ Feat, ♻️ Refactor

#161 [Feature/#157] toast 기능 추가
  package.json
  src/apis/hooks/feeds/usePatchFeed.ts
  src/apis/hooks/feeds/usePostFeed.ts
  src/apis/hooks/myPots/usePatchMyPotTodo.ts
  src/apis/hooks/pots/useCreatePot.ts
  src/apis/hooks/pots/usePatchPot.ts
  src/components/layouts/Header/Header.tsx
  src/pages/CreatePot/CreatePot.style.ts
  src/pages/CreatePot/CreatePot.tsx
  src/pages/CreatePot/components/PotForm.tsx
  src/pages/EditPost/EditPost.tsx
  src/pages/Landing/components/Step4/Step4.style.ts
  src/pages/MyPot/MyPotStatus/MyPotStatus.style.ts
  src/pages/MyPot/MyPotStatus/MyTodoModal/MyTodoModal.style.ts
  src/pages/MyPot/MyPotStatus/MyTodoModal/MyTodoModal.tsx
  src/pages/MyPot/components/MyPotTodoCard/MyPotTodoCard.tsx
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.style.ts
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx
  src/pages/WritePost/WritePost.tsx
  src/providers/SnackbarProvider.tsx
  yarn.lock
Labels: ✨ Feat, ♻️ Refactor

#164 [Feature/#135] 마이페이지 끓인 글 수정하기, 팟 어필하기 API 연동
  src/apis/hooks/pots/usePatchAppealPot.ts
  src/apis/hooks/users/useGetFinishedModal.ts
  src/apis/hooks/users/usePatchFinishedPot.ts
  src/apis/potAPI.ts
  src/apis/types/pot.ts
  src/apis/userAPI.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.tsx
  src/pages/EditFinishedPot/EditFinishedPot.tsx
  src/pages/EditFinishedPot/components/FinishedPotForm.style.ts
  src/pages/EditFinishedPot/components/FinishedPotForm.tsx
  src/pages/MyPage/components/AppealModal.tsx
  src/pages/MyPage/components/PotSummaryModal.tsx
  src/pages/Pots/MadePot/MadePot.tsx
Labels: ✨ Feat, ♻️ Refactor

#167 [Chore/#162] 1차 QA 진행
  src/assets/svgs/chevronRight.svg
  src/assets/svgs/index.ts
  src/components/commons/PotInformation/PotInformation.style.ts
  src/components/commons/PotInformation/PotInformation.tsx
  src/components/layouts/SideBar/SideBar.style.ts
  src/pages/EditPot/EditPot.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/PopularPots/PopularPots.tsx
  src/pages/Home/components/index.ts
  src/pages/Landing/Landing.style.ts
  src/pages/Landing/Landing.tsx
  src/pages/PotDetail/PotDetail.style.ts
  src/pages/PotDetail/PotDetail.tsx
  src/pages/PotDetail/components/PotHeader/PotHeader.style.ts
  src/pages/PotDetail/components/PotHeader/PotHeader.tsx
Labels: 🧹 Chore, 💄 Style

#160 [Refactor/#158] 끓인팟 상세 모달 / 어필하기 모달 레이아웃 수정
  src/assets/svgs/create.svg
  src/pages/MyPage/components/AppealModal.style.ts
  src/pages/MyPage/components/PotSummaryModal.style.ts
  src/pages/MyPage/components/PotSummaryModal.tsx
Labels: ♻️ Refactor, 💄 Style

#172 [Feature/#166] 프로필/닉네임 클릭 시 userpage 이동
  src/components/cards/PostCard/PostCard.tsx
  src/components/cards/PotCard/PotCard.tsx
  src/pages/FeedDetail/FeedDetail.tsx
  src/pages/PotDetail/PotDetail.tsx
  src/pages/PotDetail/components/ProfileInformation/ProfileInformation.tsx
Labels: ♻️ Refactor

#175 [Refactor/#174] 모달 스타일 변경
  src/components/commons/Modal/Modal.style.ts
Labels: ♻️ Refactor, 💄 Style

#178 [Refactor/#177] 피드제목 글자수 제한, 랜딩 버튼 내용 변경
  src/components/commons/PostFoam/PostFoam.tsx
  src/pages/EditFinishedPot/EditFinishedPot.tsx
  src/pages/Landing/Landing.tsx
Labels: ♻️ Refactor

#171 [Refactor/#169] 캘린더 수정
  src/pages/MyPot/MyPotCalendar/MyPotCalendar.style.ts
  src/pages/MyPot/MyPotCalendar/MyPotCalendar.tsx
Labels: ♻️ Refactor, 💄 Style

#180 [Refactor/#179] 밀림 현상 방지
  src/components/cards/FinishedPotCard/FinishedPotCard.style.ts
Labels: ♻️ Refactor, 💄 Style

#186 [Refactor/#185] 팟 생성 폼 빈칸 제출 시 스낵바 띄우기
  src/pages/CreatePot/components/PotForm.tsx
Labels: ♻️ Refactor

#184 [Refactor/ #183] 다른 사람 페이지 피드 수정 불가능
  src/apis/feedAPI.ts
  src/apis/hooks/feeds/useDeleteFeed.ts
  src/apis/hooks/users/usePatchFinishedPot.ts
  src/components/cards/PostCard/PostCard.tsx
  src/pages/EditPost/EditPost.tsx
  src/pages/FeedDetail/FeedDetail.style.ts
  src/pages/FeedDetail/FeedDetail.tsx
  src/pages/Home/components/Feed/Feed.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/pages/UserPage/UserPage.tsx
Labels: ✨ Feat, ♻️ Refactor, 💄 Style

#165 [Feature/#155] Task 생성, Task 상태 변경 api 연결, 나의팟 리팩토링
  src/apis/hooks/myPots/useDeleteMyPotTask.ts
  src/apis/hooks/myPots/useGetMyPotTask.ts
  src/apis/hooks/myPots/useGetMyPotTaskDetail.ts
  src/apis/hooks/myPots/useGetMyPotTodo.ts
  src/apis/hooks/myPots/usePatchMyPotStatus.ts
  src/apis/hooks/myPots/usePatchMyPotTask.ts
  src/apis/hooks/myPots/usePatchMyPotTask.tsx
  src/apis/hooks/myPots/usePatchMyPotTodoStatus.ts
  src/apis/hooks/myPots/usePostMyPotTask.ts
  src/apis/myPotAPI.ts
  src/apis/types/myPot.ts
  src/components/cards/TaskCard/TaskCard.tsx
  src/components/commons/Badge/Badge.style.ts
  src/components/commons/Badge/DdayBadge/DdayBadge.style.ts
  src/components/commons/Badge/StateBadge/StateBadge.style.ts
  src/components/commons/Badge/StateBadge/StateBadge.tsx
  src/components/commons/Button/Button.tsx
  src/components/commons/Button/CheckBox/CheckBox.tsx
  src/components/commons/Dropdown/MyFeedDropdown/MyFeedDropdown.tsx
  src/pages/MyPot/MyPotMain.style.ts
  src/pages/MyPot/MyPotMain.tsx
  src/pages/MyPot/MyPotStatus/AboutWorkModal/AboutWorkModal.tsx
  src/pages/MyPot/MyPotStatus/MyPotStatus.style.ts
  src/pages/MyPot/MyPotStatus/MyTodoModal/MyTodoModal.tsx
  src/pages/MyPot/MyPotStatus/TaskDetail/TaskDetail.style.ts
  src/pages/MyPot/MyPotStatus/TaskDetail/TaskDetail.tsx
  src/pages/MyPot/components/AboutWorkModalWrapper/AboutWorkModalWrapper.style.ts
  src/pages/MyPot/components/AboutWorkModalWrapper/AboutworkModalWrapper.tsx
  src/pages/MyPot/components/ActionButton/ActionButton.style.ts
  src/pages/MyPot/components/ActionButton/ActionButton.tsx
  src/pages/MyPot/components/ActionButton/CustomButton/CustomButton.tsx
  src/pages/MyPot/components/ChangeStatusModal/ChangeStatusModal.style.ts
  src/pages/MyPot/components/ChangeStatusModal/ChangeStatusModal.tsx
  src/pages/MyPot/components/ChangeStatusModal/ChangeStatusModalWrapper/ChangeStatusModalWrapper.style.ts
  src/pages/MyPot/components/ChangeStatusModal/ChangeStatusModalWrapper/ChangeStatusModalWrapper.tsx
  src/pages/MyPot/components/ContributorList/ContributorList.style.ts
  src/pages/MyPot/components/ContributorList/ContributorList.tsx
  src/pages/MyPot/components/MyPotStatusHeader/MyPotStatusHeader.tsx
  src/pages/MyPot/components/MyPotTodoCard/MyPotTodoCard.tsx
  src/pages/MyPot/components/MyPotTodoList/MyPotTodoList.tsx
  src/pages/MyPot/components/StateBadgeSelect/StateBadgeSelect.tsx
  src/pages/MyPot/components/index.ts
  src/routes/router.tsx
Labels: ✨ Feat, ♻️ Refactor, 💄 Style

#187 [Refactor/#159] QA 팟 관련 수정
  src/apis/hooks/pots/useStartPot.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.style.ts
  src/components/cards/FinishedPotCard/FinishedPotCard.tsx
  src/components/commons/PotInformation/PotInformation.style.ts
  src/components/commons/PotInformation/PotInformation.tsx
  src/pages/PotDetail/PotDetail.tsx
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx
  src/pages/PotDetail/components/MemberKakaoIdModal/MemberKakaoIdModal.tsx
  src/pages/PotDetail/components/PotHeader/PotHeader.tsx
  src/pages/Pots/AppliedPot/AppliedPot.tsx
  src/pages/Pots/components/PotInformationCard.tsx
Labels: ♻️ Refactor

#192 [Bugfix/#191] 로그인 시 프로필 안 뜨는 문제 해결
  src/apis/hooks/myPots/useGetMyPotTodo.ts
  src/apis/hooks/users/useGetSignIn.ts
  src/components/layouts/Header/Header.tsx
  src/pages/MyPot/MyPotStatus/AboutWorkModal/AboutWorkModal.tsx
  src/pages/SignUp/SignUp.tsx
  src/stores/useAuthStore.ts
  src/types/role.ts
Labels: 🐛 Fix

#194 [Hotfix/#193] 비로그인 시 home 진입 불가 문제 해결
  src/apis/hooks/feeds/useDeleteFeed.ts
  src/components/cards/PostCard/PostCard.tsx
Labels: 🐛 Fix

#189 [Refactor/#188] 컴포넌트 스타일 수정
  src/assets/svgs/pencil.svg
  src/components/commons/FloatingButton/FloatingButton.style.ts
  src/components/commons/FloatingButton/FloatingButton.tsx
  src/pages/SignUp/components/ProfileModal/ProfileModal.style.ts
  src/pages/SignUp/components/ProfileModal/ProfileModal.tsx
Labels: ♻️ Refactor, 💄 Style

#197 [Feature/#196] Feed Detail 개행 문자 처리
  src/pages/FeedDetail/FeedDetail.tsx
Labels: ✨ Feat

#201 [Refactor/#200] 홈 배너 문구 띄어쓰기
  src/pages/Home/Home.tsx
  src/pages/MyPot/MyPotCalendar/MyPotCalendar.style.ts
Labels: ♻️ Refactor
