Repository STACKPOT/STACKPOT-FE, pull requests merged in 2025-07, with the labels that each got.

#233 [Feature/#227] 모달 수정
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/commons/Modal/Modal.style.ts
  src/components/commons/Modal/Modal.tsx
Labels: ✨ Feat, ♻️ Refactor

#236 [Feature/#223] 팟 상세 페이지 수정
  src/assets/svgs/icons/circleCheck.svg
  src/assets/svgs/icons/computer.svg
  src/assets/svgs/icons/dateRange.svg
  src/assets/svgs/icons/fillCircleCheck.svg
  src/assets/svgs/icons/flag.svg
  src/assets/svgs/icons/index.ts
  src/assets/svgs/icons/supervisedUserCircle.svg
  src/assets/svgs/icons/webTraffic.svg
  src/components/cards/MemberCard/MemberCard.style.ts
  src/components/cards/MemberCard/MemberCard.tsx
  src/components/cards/RoleCard/RoleCard.style.ts
  src/components/cards/RoleCard/RoleCard.tsx
  src/components/commons/Badge/DdayBadge/DdayBadge.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/PotInformation/PotInformation.style.ts
  src/components/commons/PotInformation/PotInformation.tsx
  src/components/index.ts
  src/constants/categories.ts
  src/mocks/applicantsData.ts
  src/pages/PotDetail/PotDetail.style.ts
  src/pages/PotDetail/PotDetail.tsx
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.style.ts
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx
  src/pages/PotDetail/components/ApplyModal/ApplyModal.style.ts
  src/pages/PotDetail/components/ApplyModal/ApplyModal.tsx
  src/pages/PotDetail/components/ApplyProfileModal/ApplyProfileModal.style.ts
  src/pages/PotDetail/components/ApplyProfileModal/ApplyProfileModal.tsx
  src/pages/PotDetail/components/PotHeader/PotHeader.style.ts
  src/pages/PotDetail/components/PotHeader/PotHeader.tsx
  src/pages/PotDetail/components/ProfileInformation/ProfileInformation.style.ts
  src/pages/PotDetail/components/ProfileInformation/ProfileInformation.tsx
  src/pages/PotDetail/components/StartPotModal/StartPotModal.style.ts
  src/pages/PotDetail/components/StartPotModal/StartPotModal.tsx
  src/pages/PotDetail/components/index.ts
Labels: ✨ Feat, ♻️ Refactor

#239 [Feature/#221] 설정 페이지 모달 수정
  src/components/commons/Modal/Modal.tsx
  src/pages/Setting/Setting.style.ts
  src/pages/Setting/Setting.tsx
  src/pages/Setting/components/RoleUpdate.tsx
Labels: ✨ Feat

#246 [Refactor/#245] 실시간 인기 팟 조회 수정
  src/components/cards/PotCard/PotCard.style.ts
  src/components/layouts/SideBar/SideBar.style.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/PopularPots/PopularPots.style.ts
  src/pages/Home/components/PopularPots/PopularPots.tsx
  src/styles/global.ts
Labels: ♻️ Refactor, 💄 Style

#248 [Feature/#247] 팟 저장 API 연결
  src/apis/hooks/saves/useSavePot.ts
  src/apis/saveAPI.ts
  src/apis/types/pot.ts
  src/assets/svgs/icons/index.ts
  src/assets/svgs/icons/saveFilled.svg
  src/components/cards/PotCard/PotCard.style.ts
  src/components/cards/PotCard/PotCard.tsx
  src/pages/Home/components/PopularPots/PopularPots.tsx
  src/pages/Pots/pages/AllPot/AllPotPage.tsx
Labels: ✨ Feat

#238 [Feature/#220] 시리즈 편집 모달 추가
  src/assets/svgs/icons/info.svg
  src/components/commons/InformationPopper/InformationPopper.style.ts
  src/components/commons/InformationPopper/InformationPopper.tsx
  src/components/commons/TemperatureBar/TemperatureBar.tsx
  src/pages/MyPage/components/MyPageContent/MyPageContent.style.ts
  src/pages/MyPage/components/MyPageContent/MyPageContent.tsx
  src/pages/MyPage/components/SeriesModal/SeriesModal.style.ts
  src/pages/MyPage/components/SeriesModal/SeriesModal.tsx
Labels: ✨ Feat

#255 Delete .github/workflows/static.yml
  .github/workflows/static.yml
Labels: 🏢 Build

#262 [Refactor/#261] 업무 삭제 경고 모달 부분 로직 개선
  src/components/cards/TaskCard/TaskCard.tsx
  src/pages/MyPotDetail/components/AboutWorkModal/AboutWorkModal.style.ts
  src/pages/MyPotDetail/components/AboutWorkModal/AboutWorkModal.tsx
  src/pages/MyPotDetail/components/AboutWorkModalWrapper/AboutWorkModalWrapper.style.ts
  src/pages/MyPotDetail/components/AboutWorkModalWrapper/AboutworkModalWrapper.tsx
  src/pages/MyPotDetail/components/ActionButton/ActionButton.style.ts
  src/pages/MyPotDetail/components/ActionButton/ActionButton.tsx
  src/pages/MyPotDetail/components/ActionButton/CustomButton/CustomButton.tsx
  src/pages/MyPotDetail/components/ConfirmModalWrapper/ConfirmModalWrapper.style.ts
  src/pages/MyPotDetail/components/ConfirmModalWrapper/ConfirmModalWrapper.tsx
  src/pages/MyPotDetail/components/index.ts
  src/pages/TaskDetail/TaskDetail.tsx
Labels: ✨ Feat, ♻️ Refactor

#252 [Feature/#251] 캘린더 페이지 구현
  package-lock.json
  package.json
  src/apis/types/chat.ts
  src/assets/svgs/objects/index.ts
  src/assets/svgs/objects/workGroup.svg
  src/main.tsx
  src/mocks/chatHandler.ts
  src/pages/Chat/Chat.tsx
  src/pages/MyPotDetail/pages/MyPotCalendar/MyPotCalendar.style.ts
  src/pages/MyPotDetail/pages/MyPotCalendar/MyPotCalendar.tsx
  src/pages/MyPotDetail/pages/MyPotCalendar/components/TaskBox/TaskBox.style.ts
  src/pages/MyPotDetail/pages/MyPotCalendar/components/TaskBox/TaskBox.tsx
  yarn.lock
Labels: ✨ Feat, ♻️ Refactor

#263 [Feature/#249] 팟 만들기 페이지
  src/apis/types/pot.ts
  src/assets/svgs/icons/circleCheck.svg
  src/components/commons/CharacterCheckbox/ChacracterCheckbox.style.ts
  src/components/commons/CharacterCheckbox/CharacterCheckbox.tsx
  src/constants/categories.ts
  src/pages/CreatePot/components/DatePicker/DatePicker.style.ts
  src/pages/CreatePot/components/DatePicker/DatePicker.tsx
  src/pages/CreatePot/components/FormBody/FormBody.style.tsx
  src/pages/CreatePot/components/FormBody/FormBody.tsx
  src/pages/CreatePot/components/FormHeader/FormHeader.style.ts
  src/pages/CreatePot/components/FormHeader/FormHeader.tsx
  src/pages/CreatePot/components/PotForm.tsx
Labels: ✨ Feat

#264 [Refactor/#256] 피드 작성 페이지 수정
  src/apis/feedAPI.ts
  src/apis/hooks/feeds/useGetFeedSeries.ts
  src/apis/hooks/feeds/usePostFeed.ts
  src/apis/types/feed.ts
  src/components/commons/Button/Button.style.ts
  src/components/commons/PostForm/PostForm.style.ts
  src/components/commons/PostForm/PostForm.tsx
  src/constants/categories.ts
  src/pages/EditPost/EditPost.style.ts
  src/pages/EditPost/EditPost.tsx
  src/pages/WritePost/WritePost.style.ts
  src/pages/WritePost/WritePost.tsx
  src/types/interest.ts
Labels: ✨ Feat

#267 [Refactor/#266] 나의 팟 페이지 수정
  package-lock.json
  package.json
  src/assets/svgs/objects/chat.svg
  src/assets/svgs/objects/index.ts
  src/assets/svgs/objects/pot.svg
  src/components/cards/TaskCard/TaskCard.tsx
  src/pages/MyPotDetail/MyPotDetail.style.ts
  src/pages/MyPotDetail/MyPotDetail.tsx
  src/pages/MyPotDetail/components/AboutWorkModal/AboutWorkModal.style.ts
  src/pages/MyPotDetail/components/AboutWorkModal/AboutWorkModal.tsx
  src/pages/MyPotDetail/components/SelectTaskMemberModal/SelectTaskMemberModal.tsx
  src/pages/MyPotDetail/pages/MyPotCalendar/MyPotCalendar.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/MyPotStatus.style.ts
  src/pages/MyPotDetail/pages/MyPotStatus/MyPotStatus.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/MyPotStatusHeader/MyPotStatusHeader.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/MyPotTodoCard/MyPotTodoCard.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/MyTodoModal/MyTodoModal.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/MyTodoModalWrapper/MyTodoModalWrapper.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/StatusBar/StatusBar.style.ts
  src/pages/MyPotDetail/pages/MyPotStatus/components/StatusBar/StatusBar.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/Statusboard/StatusBoard.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/index.ts
  src/pages/TaskDetail/TaskDetail.tsx
  src/styles/theme.ts
  yarn.lock
Labels: 🌱 Add, ♻️ Refactor
