Repository STACKPOT/STACKPOT-FE, pull requests merged in 2025-08, with the labels that each got.

#269 [Refactor/#268] 나의 팟 페이지 TODO 그룹 컴포넌트 수정 및 TaskCard 수정
  src/components/cards/TaskCard/TaskCard.style.ts
  src/components/cards/TaskCard/TaskCard.tsx
  src/components/commons/Dropdown/MyFeedDropdown/MyFeedDropdown.style.ts
  src/components/commons/Pagination/Pagination.tsx
  src/components/commons/Pagination/pagination.style.ts
  src/components/index.ts
  src/pages/Home/components/PopularPots/PopularPots.style.ts
  src/pages/Home/components/PopularPots/PopularPots.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/MyPotStatus.style.ts
  src/pages/MyPotDetail/pages/MyPotStatus/MyPotStatus.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/MyPotTodoCard/MyPotTodoCard.style.ts
  src/pages/MyPotDetail/pages/MyPotStatus/components/MyPotTodoCard/MyPotTodoCard.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/MyPotTodoList/MyPotTodoList.style.ts
  src/pages/MyPotDetail/pages/MyPotStatus/components/MyPotTodoList/MyPotTodoList.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/Pagination/Pagination.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/Statusboard/StatusBoard.tsx
  src/pages/MyPotDetail/pages/MyPotStatus/components/index.ts
  src/pages/TaskDetail/TaskDetail.tsx
Labels: ♻️ Refactor, 💄 Style

#271 Feature/#220 마이페이지 소개글 API 반영
  src/apis/hooks/users/usePatchDescription.ts
  src/apis/types/pot.ts
  src/apis/types/user.ts
  src/apis/userAPI.ts
  src/pages/MyPage/components/MyPageContent/MyPageContent.tsx
Labels: ✨ Feat

#273 Feature/#249 팟 생성 화면 예상 기간 수정
  src/apis/types/pot.ts
  src/pages/CreatePot/components/FormBody/FormBody.tsx
  src/pages/CreatePot/components/PotForm.tsx
Labels: ♻️ Refactor

#272 Feature/#215 채팅 API 연동
  index.html
  package-lock.json
  src/apis/hooks/chats/useGetChatMessages.ts
  src/apis/types/chat.ts
  src/apis/types/myPot.ts
  src/apis/types/pot.ts
  src/apis/types/user.ts
  src/apis/userAPI.ts
  src/assets/svgs/icons/index.ts
  src/hooks/useChatSocket.ts
  src/mocks/chatHandler.ts
  src/mocks/memberListData.ts
  src/mocks/myPageHandler.ts
  src/pages/Chat/Chat.tsx
  src/pages/Home/components/Feed/Feed.tsx
  src/pages/Setting/Setting.tsx
  src/pages/Setting/components/CatetorySelection.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/components/CategorySelection/CategorySelection.tsx
  src/utils/dateUtils.ts
  yarn.lock
Labels: ✨ Feat

#276 [Refactor/#270] 검색 페이지 수정
  src/apis/hooks/saves/useSavePot.ts
  src/apis/types/search.ts
  src/assets/svgs/icons/search.svg
  src/components/cards/PostCard/PostCard.tsx
  src/components/commons/SearchInput/SearchInput.style.ts
  src/components/commons/SearchInput/SearchInput.tsx
  src/components/layouts/Header/Header.style.ts
  src/pages/Search/Search.style.ts
  src/pages/Search/Search.tsx
  src/pages/SearchResult/SearchResult.style.ts
  src/pages/SearchResult/SearchResult.tsx
Labels: ♻️ Refactor, 💄 Style

#282 [Feature/#281] 버튼 추가 및 권한 위임 모달 퍼블리싱
  src/components/cards/MemberCard/MemberCard.tsx
  src/pages/MyPotDetail/MyPotDetail.style.ts
  src/pages/MyPotDetail/MyPotDetail.tsx
  src/pages/MyPotDetail/components/SelectTaskMemberModal/SelectTaskMemberModal.style.ts
Labels: ✨ Feat

#265 [Refactor/#254] 나의 팟 전체화면 및 팟 끓이기 수정
  src/apis/hooks/pots/useGetPotDetail.ts
  src/apis/types/myPot.ts
  src/apis/types/pot.ts
  src/assets/svgs/icons/index.ts
  src/assets/svgs/icons/wand_star.svg
  src/components/cards/OnGoingPotCard/OnGoingPotCard.style.ts
  src/components/cards/OnGoingPotCard/OnGoingPotCard.tsx
  src/components/cards/PotDetailCard/MyPotCard.style.ts
  src/components/cards/PotDetailCard/MyPotCard.tsx
  src/components/commons/Button/CategoryButton/CategoryButton.style.ts
  src/components/commons/Button/CategoryButton/CategoryButton.tsx
  src/components/commons/PartRecruitment/PartRecruitment.tsx
  src/components/commons/PostForm/PostForm.tsx
  src/components/index.ts
  src/constants/routes.ts
  src/pages/CreateFinishedPot/CreateFinishedPot.style.ts
  src/pages/CreateFinishedPot/CreateFinishedPot.tsx
  src/pages/CreatePot/components/FormBody/FormBody.tsx
  src/pages/EditFinishedPot/components/AiButton.style.ts
  src/pages/EditFinishedPot/components/AiButton.tsx
  src/pages/EditFinishedPot/components/FinishedPotForm.style.ts
  src/pages/EditFinishedPot/components/FinishedPotForm.tsx
  src/pages/EditFinishedPot/components/SummaryLoadingModal.style.ts
  src/pages/EditFinishedPot/components/SummaryLoadingModal.tsx
  src/pages/FinishedPotDetail/FinishedPotDetail.style.ts
  src/pages/FinishedPotDetail/FinishedPotDetail.tsx
  src/pages/Home/components/Feed/Feed.tsx
  src/pages/MyPots/MyPots.style.ts
  src/pages/MyPots/MyPots.tsx
  src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx
  src/pages/PotDetail/components/StartPotModal/StartPotModal.tsx
  src/pages/Pots/pages/AllPot/AllPotPage.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/pages/Setting/components/CatetorySelection.tsx
  src/pages/SignUp/components/CategorySelection/CategorySelection.tsx
  src/pages/index.ts
  src/routes/router.tsx
  yarn.lock
Labels: ✨ Feat

#292 [Feature/#279] 닉네임 모달 구현
  src/apis/hooks/users/usePostNickname.ts
  src/assets/images/characters/index.ts
  src/assets/images/characters/sprout.webp
  src/components/commons/Modal/ExplainModal/ExplainModal.style.ts
  src/components/commons/Modal/ExplainModal/ExplainModal.tsx
  src/components/layouts/Header/Header.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/components/CompleteModal/CompleteModal.style.ts
  src/pages/SignUp/components/CompleteModal/CompleteModal.tsx
  src/pages/SignUp/components/ProfileModal/ProfileModal.style.ts
  src/pages/SignUp/components/ProfileModal/ProfileModal.tsx
  src/stores/useAuthStore.ts
Labels: ✨ Feat
